CREATE USER AD_TEMA_03_RECIBOS IDENTIFIED BY AD_TEMA_03_RECIBOS;
GRANT CONNECT, RESOURCE,DBA TO AD_TEMA_03_RECIBOS;

CREATE TABLE FORMA_PAGO(
CODIGO VARCHAR2(3),
DESCRIPCION VARCHAR2(100) NOT NULL,
N_RECIBO NUMBER(3) DEFAULT 1 NOT NULL ,
INTERES NUMBER(5, 2) DEFAULT 0 NOT NULL
);
ALTER TABLE FORMA_PAGO ADD CONSTRAINT PK_FORMA_PAGO_CODIGO PRIMARY KEY(CODIGO);

CREATE TABLE PRESTAMO(
N_PRESTAMO NUMBER(10, 6),
FECHA DATE DEFAULT SYSDATE NOT NULL ,
IMPORTE NUMBER(12, 2) DEFAULT 0 NOT NULL ,
IMPORTE_PAGADO NUMBER(12, 2) DEFAULT 0 NOT NULL ,
CODIGO_FORMA_PAGO VARCHAR2(3) NOT NULL
);
ALTER TABLE PRESTAMO ADD CONSTRAINT FK_PRESTAMO_CODIGO_FORMA_PAGO
FOREIGN KEY(CODIGO_FORMA_PAGO) REFERENCES FORMA_PAGO(CODIGO);
ALTER TABLE PRESTAMO ADD CONSTRAINT PK_PRESTAMO_N_PRESTAMO PRIMARY KEY(N_PRESTAMO);

CREATE TABLE RECIBO(
N_PRESTAMO NUMBER(10, 6),
N_RECIBO NUMBER(10),
FECHA DATE,
IMPORTE NUMBER(10, 2) DEFAULT 0 NOT NULL ,
FECHA_PAGADO DATE
);
ALTER TABLE RECIBO ADD CONSTRAINT FK_RECIBO_N_PRESTAMO_PRESTAM_
FOREIGN KEY(N_PRESTAMO) REFERENCES PRESTAMO(N_PRESTAMO);
ALTER TABLE RECIBO ADD CONSTRAINT PK_RECIBO_N_PRESTAMO_PRESTAM_ PRIMARY KEY(N_PRESTAMO, N_RECIBO);
COMMIT;

INSERT INTO FORMA_PAGO VALUES('P00', 'Pago Contado.', 1, 1);
INSERT INTO FORMA_PAGO VALUES('P03', 'Pago en 3 meses.', 3, 1);
INSERT INTO FORMA_PAGO VALUES('P10', 'Pago en 10 meses.', 10, 1);
INSERT INTO FORMA_PAGO VALUES('P20', 'Pago en 20 meses.', 20, 4);
COMMIT;

--CREACION DEL TRIGGER
create or replace TRIGGER TR_PRESTAMO_INS
AFTER INSERT
ON PRESTAMO
FOR EACH ROW
DECLARE
  xAux NUMBER;
  regFORMA_PAGO FORMA_PAGO%ROWTYPE;
  xNRecibos FORMA_PAGO.N_RECIBO%TYPE;
  xImp_Recibo NUMBER := 0;
  xFecha DATE;
BEGIN
-- a. Control de Forma de Pago
  SELECT * INTO regFORMA_PAGO FROM FORMA_PAGO WHERE CODIGO = :new.CODIGO_FORMA_PAGO;
  xNRecibos := regFORMA_PAGO.N_RECIBO;
  xFecha := :new.Fecha;
  xFecha := ADD_MONTHS(xFecha,1) ;
  xImp_Recibo:= :new.IMPORTE/xNRecibos;
  xAux := 1;
  WHILE xAux <= xNRecibos LOOP
    INSERT INTO RECIBO(N_PRESTAMO,N_RECIBO,FECHA,IMPORTE)
    VALUES(:new.N_PRESTAMO,xAux,xFecha,xImp_Recibo);
    xFecha := ADD_MONTHS(xFecha,1) ;
    xAux := xAux + 1;
  END LOOP;
  EXCEPTION
    WHEN OTHERS THEN RAISE_APPLICATION_ERROR (-20001,'Error.');
END;
--CREACION DEL SEGUNDO TRIGGER
create or replace TRIGGER TR_PRESTAMO_UPD
AFTER UPDATE
ON PRESTAMO
FOR EACH ROW
WHEN (new.fecha <> old.fecha or new.importe <> old.importe or new.codigo_forma_pago <> old.codigo_forma_pago)
DECLARE
  xAux NUMBER;
  regFORMA_PAGO FORMA_PAGO%ROWTYPE;
  xNRecibos FORMA_PAGO.N_RECIBO%TYPE;
  xImp_Recibo NUMBER := 0;
  xFecha DATE;
BEGIN
-- a. Control de Forma de Pago
  SELECT * INTO regFORMA_PAGO FROM FORMA_PAGO WHERE CODIGO = :new.CODIGO_FORMA_PAGO;
  xNRecibos := regFORMA_PAGO.N_RECIBO;
  xFecha := :new.Fecha;
  xFecha := ADD_MONTHS(xFecha,1) ;
  xImp_Recibo:= :new.IMPORTE/xNRecibos;
  xAux := 1;
-- b. Borrado de los Recibos anteriores
  DELETE RECIBO WHERE n_Prestamo = :new.n_Prestamo;
  WHILE xAux <= xNRecibos LOOP
    INSERT INTO RECIBO(N_PRESTAMO,N_RECIBO,FECHA,IMPORTE)
    VALUES(:new.N_PRESTAMO,xAux,xFecha,xImp_Recibo);
    xFecha := ADD_MONTHS(xFecha,1) ;
    xAux := xAux + 1;
  END LOOP;
  EXCEPTION
    WHEN OTHERS THEN RAISE_APPLICATION_ERROR (-20001,'Error.');
END;

INSERT INTO PRESTAMO(N_PRESTAMO,FECHA,IMPORTE,CODIGO_FORMA_PAGO)
VALUES (1000,SYSDATE-11,1000,'P00');
COMMIT;
SELECT * FROM PRESTAMO;
SELECT * FROM RECIBO;
INSERT INTO PRESTAMO(N_PRESTAMO,FECHA,IMPORTE,CODIGO_FORMA_PAGO)
VALUES (1003,SYSDATE-33,3333,'P03');
COMMIT;
SELECT * FROM PRESTAMO;
SELECT * FROM RECIBO;
INSERT INTO PRESTAMO(N_PRESTAMO,FECHA,IMPORTE,CODIGO_FORMA_PAGO)
VALUES (1010,SYSDATE-111,12500,'P10');
COMMIT;
SELECT * FROM PRESTAMO;
SELECT * FROM RECIBO;
UPDATE PRESTAMO SET IMPORTE = 6000, CODIGO_FORMA_PAGO = 'P03'
WHERE N_PRESTAMO = 1010;
COMMIT;
